#!/bin/sh

tmpfile=~/.config/neomutt/tmpfile

if \[ -z "$1" \]; then
    ranger ~/Pictures --choosefiles $tmpfile &&    # Use Ranger
    #vifm --choose-files $tmpfile &&       # Use Vifm
    sed -i 's/ /^V /g' $tmpfile &&
    echo "$(awk 'BEGIN {printf "%s", "push "} {printf "%s", "<attach-file>\""$0"\"<enter>"}'  $tmpfile)" > $tmpfile
elif \[ $1 == "clean" \]; then
    rm $tmpfile
fi
